### ISSUE TITLE
Where does this communicate with newrelic's API?

### ISSUE THREAD

**Issue by drnic** [nebhale/new-relic-service-broker#1]
@nebhale mate, I'm sorry if I'm not reading this Java app correctly - where does this service broker communicate with the New Relic API to provision/deprovision etc?

**Comment by nebhale** [comment]
It doesn't communicate with New Relic to provision/de-provision etc.  As stated in the first sentence of the `README` (:wink:):

> This project is a self-hostable application that provides a service broker that proxies New Relic credentials to applications.

The project is intended for companies that already have a New Relic account and want to be able to expose it to their Cloud Foundry-based applications without requiring a user provided service (_ick_).  Think of it as a way of proxying existing credentials (this has applications far beyond simply New Relic which is why the code is over-engineered into a "generic" solution) to applications.

As far as I'm aware there is no public New Relic API for the creation and deletion of accounts.  If there was, I'm not sure I'd want to be in the business of writing code that moves credit card numbers over the wire. :smile:

**Comment by drnic** [comment]
Ahh, so it sounds like this is an incarnation of a generic "just share the same credentials hash with everyone" in https://github.com/cloudfoundry-community/worlds-simplest-service-broker

Thanks!
